In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib as plt

ImportError: C extension: pandas.compat.numpy not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext' to build the C extensions first.

In [ ]:
df= pd.read_csv('nyc_311_data_2022.csv')

In [ ]:
df

,unique_key,created_date,closed_date,agency,agency_name,complaint_type,descriptor,location_type,incident_zip,city,landmark,status,bbl,borough,latitude,longitude
0,56415040,2022-12-31T23:59:25.000,2023-01-01T00:24:01.000,NYPD,New York City Police Department,Illegal Fireworks,NaN,Street/Sidewalk,11218.0,BROOKLYN,OCEAN PARKWAY,Closed,3.053750e+09,BROOKLYN,40.638927,-73.973250
1,56418476,2022-12-31T23:59:13.000,2023-01-01T00:26:51.000,NYPD,New York City Police Department,Noise - Street/Sidewalk,Loud Music/Party,Street/Sidewalk,10033.0,NEW YORK,WEST 184 STREET,Closed,1.021650e+09,MANHATTAN,40.851187,-73.932670
2,56415364,2022-12-31T23:59:12.000,2023-01-01T01:00:18.000,NYPD,New York City Police Department,Noise - Residential,Banging/Pounding,Residential Building/House,11226.0,BROOKLYN,OCEAN AVENUE,Closed,3.051230e+09,BROOKLYN,40.645124,-73.960077
3,56414786,2022-12-31T23:59:04.000,2023-01-03T07:49:56.000,DOHMH,Department of Health and Mental Hygiene,Rodent,Signs of Rodents,3+ Family Apt. Building,10035.0,NEW YORK,2 AVENUE,Closed,1.017970e+09,MANHATTAN,40.801435,-73.934432
4,56414075,2022-12-31T23:58:52.000,2023-01-01T00:29:43.000,NYPD,New York City Police Department,Illegal Parking,Blocked Hydrant,Street/Sidewalk,11385.0,RIDGEWOOD,CORNELIA STREET,Closed,4.035470e+09,QUEENS,40.699215,-73.906590
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299995,56087807,2022-11-25T22:31:52.000,2022-11-25T22:55:07.000,NYPD,New York City Police Department,Blocked Driveway,No Access,Street/Sidewalk,11203.0,BROOKLYN,EAST 54 STREET,Closed,3.046600e+09,BROOKLYN,40.654544,-73.926763
299996,56084623,2022-11-25T22:31:48.000,2022-11-25T23:14:52.000,NYPD,New York City Police Department,Noise - Vehicle,Car/Truck Horn,Street/Sidewalk,10463.0,BRONX,WEST 237 STREET,Closed,2.059180e+09,BRONX,40.888337,-73.913486
299997,56084378,2022-11-25T22:31:48.000,2022-11-25T22:50:45.000,NYPD,New York City Police Department,Encampment,NaN,Store/Commercial,11354.0,FLUSHING,MAIN STREET,Closed,4.049800e+09,QUEENS,40.760168,-73.830423
299998,56085462,2022-11-25T22:31:39.000,2022-11-26T01:02:33.000,NYPD,New York City Police Department,Blocked Driveway,No Access,Street/Sidewalk,11234.0,BROOKLYN,AVENUE L,Closed,3.078340e+09,BROOKLYN,40.623817,-73.923357
299999,56087518,2022-11-25T22:31:35.000,NaN,EDC,Economic Development Corporation,Noise - Helicopter,Other,Above Address,10001.0,NEW YORK,9 AVENUE,In Progress,1.007240e+09,MANHATTAN,40.748977,-73.999531

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 300000 entries, 0 to 299999
Data columns (total 16 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   unique_key      300000 non-null  int64
 1   created_date    300000 non-null  str
 2   closed_date     293796 non-null  str
 3   agency          300000 non-null  str
 4   agency_name     300000 non-null  str
 5   complaint_type  300000 non-null  str
 6   descriptor      294238 non-null  str
 7   location_type   262220 non-null  str
 8   incident_zip    296554 non-null  float64
 9   city            288244 non-null  str
 10  landmark        142571 non-null  str
 11  status          300000 non-null  str
 12  bbl             268508 non-null  float64
 13  borough         300000 non-null  str
 14  latitude        295918 non-null  float64
 15  longitude       295918 non-null  float64
dtypes: float64(4), int64(1), str(11)
memory usage: 36.6 MB

In [5]:
df['status'].unique()

<StringArray>
[     'Closed', 'In Progress',    'Assigned',        'Open',     'Started',
 'Unspecified',     'Pending']
Length: 7, dtype: str

In [6]:
df.drop(['closed_date','borough','descriptor','agency_name','landmark'], axis=1, inplace=True)

In [7]:
df

,unique_key,created_date,agency,complaint_type,location_type,incident_zip,city,status,bbl,latitude,longitude
0,56415040,2022-12-31T23:59:25.000,NYPD,Illegal Fireworks,Street/Sidewalk,11218.0,BROOKLYN,Closed,3.053750e+09,40.638927,-73.973250
1,56418476,2022-12-31T23:59:13.000,NYPD,Noise - Street/Sidewalk,Street/Sidewalk,10033.0,NEW YORK,Closed,1.021650e+09,40.851187,-73.932670
2,56415364,2022-12-31T23:59:12.000,NYPD,Noise - Residential,Residential Building/House,11226.0,BROOKLYN,Closed,3.051230e+09,40.645124,-73.960077
3,56414786,2022-12-31T23:59:04.000,DOHMH,Rodent,3+ Family Apt. Building,10035.0,NEW YORK,Closed,1.017970e+09,40.801435,-73.934432
4,56414075,2022-12-31T23:58:52.000,NYPD,Illegal Parking,Street/Sidewalk,11385.0,RIDGEWOOD,Closed,4.035470e+09,40.699215,-73.906590
...,...,...,...,...,...,...,...,...,...,...,...
299995,56087807,2022-11-25T22:31:52.000,NYPD,Blocked Driveway,Street/Sidewalk,11203.0,BROOKLYN,Closed,3.046600e+09,40.654544,-73.926763
299996,56084623,2022-11-25T22:31:48.000,NYPD,Noise - Vehicle,Street/Sidewalk,10463.0,BRONX,Closed,2.059180e+09,40.888337,-73.913486
299997,56084378,2022-11-25T22:31:48.000,NYPD,Encampment,Store/Commercial,11354.0,FLUSHING,Closed,4.049800e+09,40.760168,-73.830423
299998,56085462,2022-11-25T22:31:39.000,NYPD,Blocked Driveway,Street/Sidewalk,11234.0,BROOKLYN,Closed,3.078340e+09,40.623817,-73.923357
299999,56087518,2022-11-25T22:31:35.000,EDC,Noise - Helicopter,Above Address,10001.0,NEW YORK,In Progress,1.007240e+09,40.748977,-73.999531

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 300000 entries, 0 to 299999
Data columns (total 11 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   unique_key      300000 non-null  int64
 1   created_date    300000 non-null  str
 2   agency          300000 non-null  str
 3   complaint_type  300000 non-null  str
 4   location_type   262220 non-null  str
 5   incident_zip    296554 non-null  float64
 6   city            288244 non-null  str
 7   status          300000 non-null  str
 8   bbl             268508 non-null  float64
 9   latitude        295918 non-null  float64
 10  longitude       295918 non-null  float64
dtypes: float64(4), int64(1), str(6)
memory usage: 25.2 MB

In [10]:
df['location_type'].fillna(df['location_type'].mode(), inplace=True)

C:\Users\aa\AppData\Local\Temp\ipykernel_15108\1007253894.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['location_type'].fillna(df['location_type'].mode(), inplace=True)

0                    Street/Sidewalk
1                    Street/Sidewalk
2         Residential Building/House
3            3+ Family Apt. Building
4                    Street/Sidewalk
                     ...
299995               Street/Sidewalk
299996               Street/Sidewalk
299997              Store/Commercial
299998               Street/Sidewalk
299999                 Above Address
Name: location_type, Length: 300000, dtype: str

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 300000 entries, 0 to 299999
Data columns (total 11 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   unique_key      300000 non-null  int64
 1   created_date    300000 non-null  str
 2   agency          300000 non-null  str
 3   complaint_type  300000 non-null  str
 4   location_type   262220 non-null  str
 5   incident_zip    296554 non-null  float64
 6   city            288244 non-null  str
 7   status          300000 non-null  str
 8   bbl             268508 non-null  float64
 9   latitude        295918 non-null  float64
 10  longitude       295918 non-null  float64
dtypes: float64(4), int64(1), str(6)
memory usage: 25.2 MB

In [12]:
df['created_date'] = pd.to_datetime(df['created_date'])

In [13]:
df['latitude'] = pd.to_numeric(df['latitude'], errors='coerce')
df['longitude'] = pd.to_numeric(df['longitude'], errors='coerce')

In [14]:
df['latitude'].fillna(df['latitude'].median(), inplace=True)
df['longitude'].fillna(df['longitude'].median(), inplace=True)

C:\Users\aa\AppData\Local\Temp\ipykernel_15108\943084634.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['latitude'].fillna(df['latitude'].median(), inplace=True)
C:\Users\aa\AppData\Local\Temp\ipykernel_15108\943084634.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['longitude'].fillna(df['longitude'].median(), inplace=True)

0        -73.973250
1        -73.932670
2        -73.960077
3        -73.934432
4        -73.906590
            ...
299995   -73.926763
299996   -73.913486
299997   -73.830423
299998   -73.923357
299999   -73.999531
Name: longitude, Length: 300000, dtype: float64

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 300000 entries, 0 to 299999
Data columns (total 11 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   unique_key      300000 non-null  int64
 1   created_date    300000 non-null  datetime64[us]
 2   agency          300000 non-null  str
 3   complaint_type  300000 non-null  str
 4   location_type   262220 non-null  str
 5   incident_zip    296554 non-null  float64
 6   city            288244 non-null  str
 7   status          300000 non-null  str
 8   bbl             268508 non-null  float64
 9   latitude        295918 non-null  float64
 10  longitude       295918 non-null  float64
dtypes: datetime64[us](1), float64(4), int64(1), str(5)
memory usage: 25.2 MB

In [46]:
import time
from geopy.geocoders import Nominatim
from geopy.exc import GeocoderTimedOut, GeocoderUnavailable

# Initialize geocoder
geolocator = Nominatim(user_agent="zip_lookup")

# Safe reverse function with retry + delay
def safe_reverse(lat, lon, retries=3, delay=1):
    for attempt in range(retries):
        try:
            return geolocator.reverse((lat, lon), exactly_one=True, timeout=10)
        except (GeocoderTimedOut, GeocoderUnavailable):
            time.sleep(delay)
    return None

# Function to get ZIP from lat/lon
def get_zip(lat, lon):
    location = safe_reverse(lat, lon)
    if location and 'postcode' in location.raw['address']:
        return location.raw['address']['postcode']
    return None

# --- Step 1: Select only rows with NaN incident_zip ---
mask = df['incident_zip'].isna()
subset = df.loc[mask, ['latitude', 'longitude']].copy()

# --- Step 2: Apply geocoding only to NaNs ---
zip_codes = []
for i, row in subset.iterrows():
    zip_codes.append(get_zip(row['latitude'], row['longitude']))
    time.sleep(1)  # respect Nominatim rate limit

subset['incident_zip'] = zip_codes

# --- Step 3: Merge back into original DataFrame ---
df.loc[mask, 'incident_zip'] = subset['incident_zip']

print(df.head())

   unique_key        created_date agency           complaint_type  \
0    56415040 2022-12-31 23:59:25   NYPD        Illegal Fireworks
1    56418476 2022-12-31 23:59:13   NYPD  Noise - Street/Sidewalk
2    56415364 2022-12-31 23:59:12   NYPD      Noise - Residential
3    56414786 2022-12-31 23:59:04  DOHMH                   Rodent
4    56414075 2022-12-31 23:58:52   NYPD          Illegal Parking

                location_type incident_zip  status           bbl   latitude  \
0             Street/Sidewalk      11218.0  Closed  3.053750e+09  40.638927
1             Street/Sidewalk      10033.0  Closed  1.021650e+09  40.851187
2  Residential Building/House      11226.0  Closed  3.051230e+09  40.645124
3     3+ Family Apt. Building      10035.0  Closed  1.017970e+09  40.801435
4             Street/Sidewalk      11385.0  Closed  4.035470e+09  40.699215

   longitude
0 -73.973250
1 -73.932670
2 -73.960077
3 -73.934432
4 -73.906590

C:\Users\aio\AppData\Local\Temp\ipykernel_139568\4110117208.py:37: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['11104' '11104' '11104' ... '10019' '10105' '10003']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[mask, 'incident_zip'] = subset['incident_zip']

In [47]:
df['incident_zip'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 300000 entries, 0 to 299999
Series name: incident_zip
Non-Null Count   Dtype
--------------   -----
300000 non-null  object
dtypes: object(1)
memory usage: 2.3+ MB

In [ ]:
import requests
import time

def get_bbl(lat, lon):
    url = f"https://api.nyc.gov/geoclient/v1/latlon.json?lat={lat}&lon={lon}&app_id=YOUR_APP_ID&app_key=YOUR_APP_KEY"
    response = requests.get(url).json()
    if 'latLon' in response and 'bbl' in response['latLon']:
        return response['latLon']['bbl']
    return None

mask = df['bbl'].isna()
subset = df.loc[mask, ['latitude', 'longitude']].copy()

bbl_values = []
for i, row in subset.iterrows():
    bbl_values.append(get_bbl(row['latitude'], row['longitude']))
    time.sleep(0.5) 

subset['bbl'] = bbl_values

df.loc[mask, 'bbl'] = subset['bbl']

print(df.head())

In [ ]:
ping api.nyc.gov
APP_ID = "your_real_app_id"
APP_KEY = "your_real_app_key"
import requests
url = f"https://api.nyc.gov/geoclient/v1/latlon.json?lat=40.7128&lon=-74.0060&app_id={APP_ID}&app_key={APP_KEY}"
r = requests.get(url)
print(r.status_code, r.text)